name: build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "53 * * * *"
  workflow_dispatch:
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@2bf61fb9464cc67f0cbdeabed6aa0380accd1c70 # v5
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4
        with:
          driver: docker
      - name: Build image
        id: build
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker run --privileged --rm -e GITHUB_REPOSITORY -e GITHUB_TOKEN ${{ steps.build.outputs.imageid }}
